/* =========================================================
   BarnBound Prototype — Mock Data
   All data is sample data for demo purposes only.
   ========================================================= */

const BUSINESSES = [
  {
    id: 1,
    name: "Poudre River Stables",
    category: "Boarding",
    city: "Fort Collins, CO",
    emoji: "🏇",
    rating: 4.9,
    reviews: 48,
    tags: ["Full Care", "Indoor Arena", "Trails"],
    verified: true,
    featured: true,
    description: "Full-service boarding with indoor arena, round pen, and direct access to Poudre River trails.",
  },
  {
    id: 2,
    name: "Dr. Mitchell — Equine Veterinary",
    category: "Veterinary",
    city: "Loveland, CO",
    emoji: "🩺",
    rating: 5.0,
    reviews: 32,
    tags: ["Lameness", "Dentistry", "Mobile"],
    verified: true,
    featured: true,
    description: "Mobile equine vet serving Larimer & Weld Counties. 20+ years experience in sport horse medicine.",
  },
  {
    id: 3,
    name: "Mountain View Ranch & Stables",
    category: "Training",
    city: "Fort Collins, CO",
    emoji: "🤠",
    rating: 4.7,
    reviews: 27,
    tags: ["Western", "Reining", "Young Horses"],
    verified: true,
    featured: true,
    description: "Western performance training. Reining and ranch horse specialists with NRHA credentials.",
  },
  {
    id: 4,
    name: "Front Range Farrier Co.",
    category: "Farrier",
    city: "Windsor, CO",
    emoji: "🔨",
    rating: 4.8,
    reviews: 41,
    tags: ["Corrective", "Hot Shoeing", "Barefoot"],
    verified: true,
    featured: false,
    description: "Certified Journeyman Farrier. Corrective shoeing and lameness rehab.",
  },
  {
    id: 5,
    name: "Paradise Found Farm",
    category: "Boarding",
    city: "Wellington, CO",
    emoji: "🐴",
    rating: 4.6,
    reviews: 19,
    tags: ["Pasture", "Self Care", "Small Barn"],
    verified: true,
    featured: false,
    description: "Quiet pasture boarding on 40 acres. Small private barn atmosphere.",
  },
  {
    id: 6,
    name: "Northern Colorado Feed & Tack",
    category: "Feed & Tack",
    city: "Fort Collins, CO",
    emoji: "🛍️",
    rating: 4.8,
    reviews: 63,
    tags: ["Feed Delivery", "Western Tack", "English Tack"],
    verified: true,
    featured: true,
    description: "Full-service feed, tack, and supply. Free delivery within 20 miles.",
  },
  {
    id: 7,
    name: "Equine Sports Therapy",
    category: "Service Providers",
    city: "Longmont, CO",
    emoji: "💆",
    rating: 4.9,
    reviews: 24,
    tags: ["Massage", "Bodywork", "Rehab"],
    verified: true,
    featured: false,
    description: "Certified equine massage therapist and bodyworker. Mobile service.",
  },
  {
    id: 8,
    name: "Bighorn Trailer Transport",
    category: "Hauler",
    city: "Greeley, CO",
    emoji: "🚚",
    rating: 4.7,
    reviews: 15,
    tags: ["Long Haul", "Local", "CDL Certified"],
    verified: true,
    featured: false,
    description: "Insured horse transport. Local and cross-country hauling.",
  },
  {
    id: 9,
    name: "Soukup Stables",
    category: "Boarding",
    city: "Fort Collins, CO",
    emoji: "🏡",
    rating: 4.5,
    reviews: 22,
    tags: ["Family Owned", "Full Care", "Lessons"],
    verified: true,
    featured: false,
    description: "Family-owned boarding barn offering full care and beginner lesson programs.",
  },
  {
    id: 10,
    name: "Lily Creek Photography",
    category: "Photographer",
    city: "Fort Collins, CO",
    emoji: "📸",
    rating: 5.0,
    reviews: 38,
    tags: ["Portraits", "Events", "Sales Photos"],
    verified: true,
    featured: false,
    description: "Equine portraits, show coverage, and sales listing photography.",
  },
  {
    id: 11,
    name: "Larimer Equine Clinic",
    category: "Veterinary",
    city: "Fort Collins, CO",
    emoji: "🏥",
    rating: 4.8,
    reviews: 56,
    tags: ["Surgery", "Reproduction", "24/7"],
    verified: true,
    featured: false,
    description: "Full-service equine hospital. Surgery, reproduction, lameness, and 24/7 emergency.",
  },
  {
    id: 12,
    name: "Front Range Equine Dentistry",
    category: "Service Providers",
    city: "Berthoud, CO",
    emoji: "🦷",
    rating: 4.9,
    reviews: 29,
    tags: ["Floating", "Mobile", "Power Float"],
    verified: true,
    featured: false,
    description: "Certified equine dentist. Mobile service throughout Northern Colorado.",
  },
];

const LISTINGS = [
  {
    id: 101,
    type: "Horse",
    title: "8yr Quarter Horse Gelding — Ranch Ready",
    breed: "Quarter Horse",
    discipline: "Western / Ranch",
    age: 8,
    price: 12500,
    city: "Fort Collins, CO",
    emoji: "🐎",
    verified: true,
    featured: true,
    description: "Solid trail and ranch horse. Been everywhere, done everything. Stands for vet and farrier.",
  },
  {
    id: 102,
    type: "Horse",
    title: "6yr OTTB — Jumper Prospect",
    breed: "Thoroughbred",
    discipline: "Hunter/Jumper",
    age: 6,
    price: 18000,
    city: "Loveland, CO",
    emoji: "🏇",
    verified: true,
    featured: true,
    description: "Off-track Thoroughbred, 3 years of retraining. Brave, scopey, jumps 3' courses.",
  },
  {
    id: 103,
    type: "Tack",
    title: "Circle Y Barrel Racing Saddle — 15\"",
    category: "Saddle",
    price: 1850,
    city: "Windsor, CO",
    emoji: "🤠",
    verified: true,
    featured: false,
    description: "Barely used. Full silver, hand-tooled. Ready for the run.",
  },
  {
    id: 104,
    type: "Horse",
    title: "12yr Paint Mare — Beginner Safe",
    breed: "Paint",
    discipline: "Trail / Lesson",
    age: 12,
    price: 6500,
    city: "Greeley, CO",
    emoji: "🐴",
    verified: true,
    featured: true,
    description: "Kid-safe, husband-safe, packer. Will teach someone to ride.",
  },
  {
    id: 105,
    type: "Tack",
    title: "Antares Signature Jump Saddle 17.5\"",
    category: "Saddle",
    price: 3200,
    city: "Fort Collins, CO",
    emoji: "🎠",
    verified: true,
    featured: false,
    description: "French-made jumping saddle, narrow tree, excellent condition.",
  },
  {
    id: 106,
    type: "Equipment",
    title: "Featherlite 2-Horse Straight Load Trailer",
    category: "Trailer",
    price: 14500,
    city: "Wellington, CO",
    emoji: "🚛",
    verified: true,
    featured: false,
    description: "2018 model. All-aluminum. Well maintained, new tires.",
  },
  {
    id: 107,
    type: "Horse",
    title: "3yr Warmblood Filly — Dressage Prospect",
    breed: "Warmblood",
    discipline: "Dressage",
    age: 3,
    price: 25000,
    city: "Longmont, CO",
    emoji: "🐎",
    verified: true,
    featured: true,
    description: "Imported bloodlines, started under saddle, incredible movement.",
  },
  {
    id: 108,
    type: "Tack",
    title: "Tucker Endurance Saddle — Wide Tree",
    category: "Saddle",
    price: 950,
    city: "Berthoud, CO",
    emoji: "🪑",
    verified: true,
    featured: false,
    description: "Gently used. Perfect for long trail rides. Wide tree, soft seat.",
  },
  {
    id: 109,
    type: "Equipment",
    title: "Priefert Round Pen — 50ft, 6 Panels",
    category: "Equipment",
    price: 1600,
    city: "Fort Collins, CO",
    emoji: "🛠️",
    verified: true,
    featured: false,
    description: "Like new. Heavy-duty 12ft panels. Disassembles for transport.",
  },
  {
    id: 110,
    type: "Horse",
    title: "10yr Appaloosa Gelding — Trail Partner",
    breed: "Appaloosa",
    discipline: "Trail",
    age: 10,
    price: 8500,
    city: "Severance, CO",
    emoji: "🐴",
    verified: true,
    featured: false,
    description: "Bombproof on the trail. Crosses water, no buck, no spook.",
  },
  {
    id: 111,
    type: "Tack",
    title: "Professionals Choice SMB Boots — Set of 4",
    category: "Boots/Wraps",
    price: 120,
    city: "Fort Collins, CO",
    emoji: "👢",
    verified: true,
    featured: false,
    description: "Medium size. Hot pink. Lightly used.",
  },
  {
    id: 112,
    type: "Horse",
    title: "5yr POA Pony Gelding — Kid Jumper",
    breed: "POA",
    discipline: "Hunter/Jumper",
    age: 5,
    price: 9500,
    city: "Fort Collins, CO",
    emoji: "🐴",
    verified: true,
    featured: false,
    description: "Successful short stirrup pony. Small, brave, tidy jumper.",
  },
];

const EVENTS = [
  { id: 1, month: "Nov", day: 8, title: "Front Range Ranch Horse Clinic", meta: "Sat · Poudre River Stables · $150", category: "Clinic" },
  { id: 2, month: "Nov", day: 15, title: "Larimer County Saddle Club Show", meta: "Sat · All day · Loveland Fairgrounds", category: "Show" },
  { id: 3, month: "Nov", day: 22, title: "BarnBound Meet & Greet — Fort Collins", meta: "Sat · 2pm · NoCo Feed & Tack", category: "Community" },
  { id: 4, month: "Dec", day: 6, title: "CSU Equine Sciences Open House", meta: "Sat · 10am · CSU Equine Center", category: "Education" },
  { id: 5, month: "Dec", day: 13, title: "Winter Dressage Schooling Show", meta: "Sat · All day · Mountain View Arena", category: "Show" },
  { id: 6, month: "Jan", day: 10, title: "Beginner Barrel Racing Clinic", meta: "Sat · Soukup Stables · $125", category: "Clinic" },
];

const FORUMS = [
  { icon: "❓", title: "Best winter blanket for a hard keeper?", meta: "Posted in Horse Care · 14 replies · 2h ago" },
  { icon: "🐴", title: "Recommendations for reliable hauler to Texas?", meta: "Posted in Transport · 9 replies · 5h ago" },
  { icon: "🩺", title: "Anyone tried Equioxx long-term for an older horse?", meta: "Posted in Health · 23 replies · yesterday" },
  { icon: "🎠", title: "Saddle fitting in Northern Colorado — who do you use?", meta: "Posted in Tack · 17 replies · 2 days ago" },
  { icon: "🏆", title: "First barrel race — what should I bring?", meta: "Posted in Competition · 28 replies · 3 days ago" },
  { icon: "🌾", title: "Cutting back on alfalfa — what are you feeding?", meta: "Posted in Nutrition · 11 replies · 4 days ago" },
];

const GROUPS = [
  { icon: "🤠", title: "Front Range Western Riders", meta: "2,847 members · Active daily" },
  { icon: "🎠", title: "Larimer County Hunter/Jumper", meta: "1,423 members · Active daily" },
  { icon: "🏇", title: "CSU Equestrian & Alumni", meta: "892 members · Active weekly" },
  { icon: "🐎", title: "Northern Colorado Dressage", meta: "1,104 members · Active daily" },
  { icon: "🏃", title: "Barrel Racers of NoCo", meta: "2,112 members · Active daily" },
  { icon: "🌄", title: "Colorado Trail Riders", meta: "4,237 members · Active daily" },
];
