/* =========================================================
   BarnBound Prototype — Mock Data
   All data is sample data for demo purposes only.
   ========================================================= */

/* Real BarnBound launch partners — 11 Northern Colorado equine businesses. */
const BUSINESSES = [
  {
    id: 1,
    name: "JAX Outdoor Gear, Farm & Ranch",
    url: "https://jaxgoods.com/",
    category: "Retail",
    city: "Fort Collins, CO",
    emoji: "🛍️",
    rating: 4.8,
    reviews: 312,
    tags: ["Ranch Supply", "Livestock Feed", "Western Wear", "Outdoor Gear"],
    verified: true,
    featured: true,
    description: "Northern Colorado institution combining farm and ranch supplies, livestock feed, and outdoor gear under one roof. Stores across Fort Collins and Loveland stock fencing, animal care, work boots, western apparel, and tools for the ranching lifestyle.",
  },
  {
    id: 2,
    name: "Murdoch's Ranch & Home Supply",
    url: "https://www.murdochs.com/",
    category: "Retail",
    city: "Fort Collins, CO",
    emoji: "🤠",
    rating: 4.7,
    reviews: 248,
    tags: ["Ranch Supply", "Western Wear", "Feed & Tack", "Livestock Equipment"],
    verified: true,
    featured: true,
    description: "Regional ranch-and-home retailer carrying tack, feed, fencing, livestock equipment, western wear, and power equipment. Northern Colorado riders shop their Fort Collins, Longmont, and Parker locations.",
  },
  {
    id: 3,
    name: "LeClair Equine",
    url: "https://leclairequine.com/",
    category: "Veterinary",
    city: "Berthoud, CO",
    emoji: "🩺",
    rating: 4.9,
    reviews: 64,
    tags: ["Ambulatory Vet", "Sports Medicine", "Dentistry", "Lameness"],
    verified: true,
    featured: true,
    description: "Berthoud-based equine veterinary practice offering ambulatory field service and haul-in clinic care. Services span preventative wellness, advanced dentistry, sports medicine, lameness evaluation, acupuncture, and massage therapy.",
  },
  {
    id: 4,
    name: "Bomgaars",
    url: "https://www.bomgaars.com/",
    category: "Retail",
    city: "Fort Morgan, CO",
    emoji: "🛍️",
    rating: 4.6,
    reviews: 187,
    tags: ["Farm & Ranch", "Livestock Supply", "Hardware", "Power Equipment"],
    verified: true,
    featured: true,
    description: "Regional farm and ranch retailer serving rural communities. Colorado locations in Fort Morgan, Sterling, and Greeley carry livestock feed and health supplies, fencing, tack basics, power equipment, and workwear.",
  },
  {
    id: 5,
    name: "Tractor Supply Co.",
    url: "https://www.tractorsupply.com/",
    category: "Retail",
    city: "Loveland, CO",
    emoji: "🚜",
    rating: 4.5,
    reviews: 421,
    tags: ["Livestock Feed", "Fencing", "Tack Basics", "Farm Supply"],
    verified: true,
    featured: true,
    description: "The nation's largest rural lifestyle retailer — horse feed, hay, fencing, stall supplies, tack basics, trailer accessories, and animal health products. Northern Colorado stores in Loveland, Fort Collins, Longmont, Greeley, and Windsor.",
  },
  {
    id: 6,
    name: "The Latigo Lariat",
    url: "https://latigolariat.com/",
    category: "Feed & Tack",
    city: "Loveland, CO",
    emoji: "🤠",
    rating: 4.9,
    reviews: 89,
    tags: ["Western Tack", "Saddles", "Ropes", "Consignment"],
    verified: true,
    featured: true,
    description: "Loveland western tack shop with ~250 saddles in stock — roping, barrel, and pleasure rigs from Martin, Circle Y, and Reinsman. New, used, consignment, and trade-in saddles alongside ropes and cowboy gifts.",
  },
  {
    id: 7,
    name: "Happy Horse Tack Shop",
    url: "https://www.happyhorsetack.com/",
    category: "Feed & Tack",
    city: "Fort Collins, CO",
    emoji: "🎠",
    rating: 4.8,
    reviews: 134,
    tags: ["English Tack", "Western Tack", "Consignment", "Saddle Fitting"],
    verified: true,
    featured: true,
    description: "Full-service Northern Colorado tack shop carrying both English and Western gear — jump, all-purpose, dressage, endurance, and western saddles. Robust used/consignment program, rider apparel, and saddle fitting services.",
  },
  {
    id: 8,
    name: "Gargot Farms Equestrian Center",
    url: "https://www.gargotfarms.com/",
    category: "Boarding",
    city: "Berthoud, CO",
    emoji: "🏇",
    rating: 4.8,
    reviews: 42,
    tags: ["Boarding", "Lessons", "Pony Camp", "Youth Programs"],
    verified: true,
    featured: true,
    description: "Berthoud-based facility offering horse boarding, riding lessons, and youth pony camp programs. Community-oriented environment for riders of all ages looking for a home base in Northern Colorado.",
  },
  {
    id: 9,
    name: "Apollo Equestrian LLC",
    url: "https://www.apolloequestrianllc.com/",
    category: "Training",
    city: "Fort Collins, CO",
    emoji: "🎠",
    rating: 4.9,
    reviews: 37,
    tags: ["English Training", "Lessons", "Boarding", "Sales & Leasing"],
    verified: true,
    featured: true,
    description: "Fort Collins training barn founded in 2017 by Sarah Hughes, serving Loveland, Windsor, and Wellington. Lessons, professional training, boarding, leasing, horse sales, and a competition team.",
  },
  {
    id: 10,
    name: "Rosewood Equestrian Center",
    url: "https://www.rosewoodeqcenter.com/",
    category: "Training",
    city: "Loveland, CO",
    emoji: "🐴",
    rating: 4.8,
    reviews: 51,
    tags: ["Riding Lessons", "Training", "Hay Sales", "Boarding"],
    verified: true,
    featured: true,
    description: "Family-owned 12-acre equestrian facility in southwest Loveland offering riding lessons, horse training, and grass/alfalfa hay sales. Premium horse care with on-site vaccination clinics and emergency vet support.",
  },
  {
    id: 11,
    name: "Oleo Acres Farrier Supply",
    url: "https://www.oleoacresfarriersupply.com/",
    category: "Farrier",
    city: "Berthoud, CO",
    emoji: "🔨",
    rating: 4.9,
    reviews: 76,
    tags: ["Horseshoes", "Farrier Tools", "Forges & Anvils", "Hoof Care"],
    verified: true,
    featured: true,
    description: "Colorado-based farrier supply retailer serving equine professionals across Colorado and Wyoming from Berthoud, Littleton, and Elbert. Horseshoes, nails, rasps, hand tools, hoof care, and blacksmith equipment.",
  },
];

const LISTINGS = [
  {
    id: 101,
    type: "Horse",
    title: "8yr Quarter Horse Gelding — Ranch Ready",
    breed: "Quarter Horse",
    discipline: "Western / Ranch",
    age: 8,
    price: 12500,
    city: "Fort Collins, CO",
    emoji: "🐎",
    verified: true,
    featured: true,
    description: "Solid trail and ranch horse. Been everywhere, done everything. Stands for vet and farrier.",
  },
  {
    id: 102,
    type: "Horse",
    title: "6yr OTTB — Jumper Prospect",
    breed: "Thoroughbred",
    discipline: "Hunter/Jumper",
    age: 6,
    price: 18000,
    city: "Loveland, CO",
    emoji: "🏇",
    verified: true,
    featured: true,
    description: "Off-track Thoroughbred, 3 years of retraining. Brave, scopey, jumps 3' courses.",
  },
  {
    id: 103,
    type: "Tack",
    title: "Circle Y Barrel Racing Saddle — 15\"",
    category: "Saddle",
    price: 1850,
    city: "Windsor, CO",
    emoji: "🤠",
    verified: true,
    featured: false,
    description: "Barely used. Full silver, hand-tooled. Ready for the run.",
  },
  {
    id: 104,
    type: "Horse",
    title: "12yr Paint Mare — Beginner Safe",
    breed: "Paint",
    discipline: "Trail / Lesson",
    age: 12,
    price: 6500,
    city: "Greeley, CO",
    emoji: "🐴",
    verified: true,
    featured: true,
    description: "Kid-safe, husband-safe, packer. Will teach someone to ride.",
  },
  {
    id: 105,
    type: "Tack",
    title: "Antares Signature Jump Saddle 17.5\"",
    category: "Saddle",
    price: 3200,
    city: "Fort Collins, CO",
    emoji: "🎠",
    verified: true,
    featured: false,
    description: "French-made jumping saddle, narrow tree, excellent condition.",
  },
  {
    id: 106,
    type: "Equipment",
    title: "Featherlite 2-Horse Straight Load Trailer",
    category: "Trailer",
    price: 14500,
    city: "Wellington, CO",
    emoji: "🚛",
    verified: true,
    featured: false,
    description: "2018 model. All-aluminum. Well maintained, new tires.",
  },
  {
    id: 107,
    type: "Horse",
    title: "3yr Warmblood Filly — Dressage Prospect",
    breed: "Warmblood",
    discipline: "Dressage",
    age: 3,
    price: 25000,
    city: "Longmont, CO",
    emoji: "🐎",
    verified: true,
    featured: true,
    description: "Imported bloodlines, started under saddle, incredible movement.",
  },
  {
    id: 108,
    type: "Tack",
    title: "Tucker Endurance Saddle — Wide Tree",
    category: "Saddle",
    price: 950,
    city: "Berthoud, CO",
    emoji: "🪑",
    verified: true,
    featured: false,
    description: "Gently used. Perfect for long trail rides. Wide tree, soft seat.",
  },
  {
    id: 109,
    type: "Equipment",
    title: "Priefert Round Pen — 50ft, 6 Panels",
    category: "Equipment",
    price: 1600,
    city: "Fort Collins, CO",
    emoji: "🛠️",
    verified: true,
    featured: false,
    description: "Like new. Heavy-duty 12ft panels. Disassembles for transport.",
  },
  {
    id: 110,
    type: "Horse",
    title: "10yr Appaloosa Gelding — Trail Partner",
    breed: "Appaloosa",
    discipline: "Trail",
    age: 10,
    price: 8500,
    city: "Severance, CO",
    emoji: "🐴",
    verified: true,
    featured: false,
    description: "Bombproof on the trail. Crosses water, no buck, no spook.",
  },
  {
    id: 111,
    type: "Tack",
    title: "Professionals Choice SMB Boots — Set of 4",
    category: "Boots/Wraps",
    price: 120,
    city: "Fort Collins, CO",
    emoji: "👢",
    verified: true,
    featured: false,
    description: "Medium size. Hot pink. Lightly used.",
  },
  {
    id: 112,
    type: "Horse",
    title: "5yr POA Pony Gelding — Kid Jumper",
    breed: "POA",
    discipline: "Hunter/Jumper",
    age: 5,
    price: 9500,
    city: "Fort Collins, CO",
    emoji: "🐴",
    verified: true,
    featured: false,
    description: "Successful short stirrup pony. Small, brave, tidy jumper.",
  },
];

const EVENTS = [
  { id: 1, month: "Nov", day: 8, title: "Front Range Ranch Horse Clinic", meta: "Sat · Poudre River Stables · $150", category: "Clinic" },
  { id: 2, month: "Nov", day: 15, title: "Larimer County Saddle Club Show", meta: "Sat · All day · Loveland Fairgrounds", category: "Show" },
  { id: 3, month: "Nov", day: 22, title: "BarnBound Meet & Greet — Fort Collins", meta: "Sat · 2pm · Happy Horse Tack Shop", category: "Community" },
  { id: 4, month: "Dec", day: 6, title: "CSU Equine Sciences Open House", meta: "Sat · 10am · CSU Equine Center", category: "Education" },
  { id: 5, month: "Dec", day: 13, title: "Winter Dressage Schooling Show", meta: "Sat · All day · Mountain View Arena", category: "Show" },
  { id: 6, month: "Jan", day: 10, title: "Beginner Barrel Racing Clinic", meta: "Sat · Soukup Stables · $125", category: "Clinic" },
];

const FORUMS = [
  { icon: "❓", title: "Best winter blanket for a hard keeper?", meta: "Posted in Horse Care · 14 replies · 2h ago" },
  { icon: "🐴", title: "Recommendations for reliable hauler to Texas?", meta: "Posted in Transport · 9 replies · 5h ago" },
  { icon: "🩺", title: "Anyone tried Equioxx long-term for an older horse?", meta: "Posted in Health · 23 replies · yesterday" },
  { icon: "🎠", title: "Saddle fitting in Northern Colorado — who do you use?", meta: "Posted in Tack · 17 replies · 2 days ago" },
  { icon: "🏆", title: "First barrel race — what should I bring?", meta: "Posted in Competition · 28 replies · 3 days ago" },
  { icon: "🌾", title: "Cutting back on alfalfa — what are you feeding?", meta: "Posted in Nutrition · 11 replies · 4 days ago" },
];

const GROUPS = [
  { icon: "🤠", title: "Front Range Western Riders", meta: "2,847 members · Active daily" },
  { icon: "🎠", title: "Larimer County Hunter/Jumper", meta: "1,423 members · Active daily" },
  { icon: "🏇", title: "CSU Equestrian & Alumni", meta: "892 members · Active weekly" },
  { icon: "🐎", title: "Northern Colorado Dressage", meta: "1,104 members · Active daily" },
  { icon: "🏃", title: "Barrel Racers of NoCo", meta: "2,112 members · Active daily" },
  { icon: "🌄", title: "Colorado Trail Riders", meta: "4,237 members · Active daily" },
];
